// action常量
export const GET_ALL_MANUFACTURERS_SUCCESS = 'GET_ALL_MANUFACTURERS_SUCCESS'

export const GET_MANUFACTURER_BY_ID_SUCCESS = 'GET_MANUFACTURER_BY_ID_SUCCESS'

export const ADD_MANUFACTURER_SUCCESS = 'ADD_MANUFACTURER_SUCCESS'

export const UPDATE_MANUFACTURER_SUCCESS = 'UPDATE_MANUFACTURER_SUCCESS'

export const REMOVE_MANUFACTURER_SUCCESS = 'REMOVE_MANUFACTURER_SUCCESS'

export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'

export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'

export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'

export const ADD_CART_ITEMS = 'ADD_CART_ITEMS'

export const ADD_CART_ITEM = 'ADD_CART_ITEM'

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'

export const WILL_UPDATE_CART_ITEM = 'WILL_UPDATE_CART_ITEM'

export const PRELOAD = 'PRELOAD'

export const LOADED = 'LOADED'

export const ERROR = 'ERROR'
